url: http://web.stanford.edu/class/cs147/projects/behavior/The_Penguins
baseurl: 

# Site settings
title: Instagator
email: amcnary@stanford.edu
description: "Instagator is an awesome platform that helps make planning group travel easy, interactive, and fun! Get your people involved and prepare for an awesome trip!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 546426
  secondary: 22d207  
  secondary-dark: 111111

# Team names, titles and social links
people:
- name: Rhea D
  pic: rhea
  position: Founder and CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Dennis E
  pic: dennis
  position: Founder and CFO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Tanner G
  pic: tanner
  position: Founder and CTO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- name: Amanda M
  pic: amanda
  position: Founder and CMO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Stanford, CA 90210

# Build settings
markdown: kramdown
permalink: pretty